name: Hello Pipeline

on:
  push:
    branches: [ lab03 ]
  workflow_dispatch:
    

jobs:
  run-lab2-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Clean install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Make script executable
        run: chmod +x ./deliverables/lab02/lab2.sh

      - name: Run lab2.sh
        run: ./deliverables/lab02/lab2.sh
