name: Hello Pipeline

on:
  push:
    branches:
      - lab03

jobs:
  run-lab2-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run lab2.sh
        run: ./deliverables/lab02/lab2.sh
