name: Hello Pipeline

on:
  push:
    branches: [ lab03 ]
  workflow_dispatch:
    

jobs:
  run-lab2-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Check outdated dependencies
        run: |
          mkdir -p reports
          pnpm outdated --format json > reports/outdated-dependencies.json || true

      - name: Security audit
        run: pnpm audit --json > reports/vulnerable-dependencies.json || true

      - name: Type check
        run: pnpm nuxt typecheck

      - name: Build
        run: pnpm nuxt build

      - name: Lint
        run: pnpm eslint .

      - name: Test
        run: pnpm vitest run

      - name: Upload dependency reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-reports
          path: reports/
